### ISSUE TITLE
Support Free Practice and Quali sessions

### ISSUE THREAD

**Issue by rhortal** [eHonnef/py-jellyfin-metadata-generator#1]
Thanks for creating this!
I was wondering if it would be possible to extend the software to also recognise and label the rest of the weekends' sessions - qualification and free practice.
Thanks you.

**Comment by eHonnef** [comment]
Yes, it is possible, I would assume that your files are named like:

- Formula 1 - s2023e20 - Sao Paulo Grand Prix - Free practice - 2160p50.mp4
- Formula 1 - s2023e20 - Sao Paulo Grand Prix - Qualification - 2160p50.mp4

Then I can check on that, no problem.

**Comment by eHonnef** [comment]
Now this should be supported with the last commit [fe3d620](https://github.com/eHonnef/py-jellyfin-metadata-generator/commit/fe3d62083a78a4d1638b87c220e466f259a02fff).

It was also added some improvements regarding the usability of the tool, check out the [README](https://github.com/eHonnef/py-jellyfin-metadata-generator/blob/master/formula1/README.md) for more details and let me know if you found any problems.

Cheers :)
