### ISSUE TITLE
Missing config.json

### ISSUE THREAD

**Issue by kristgn** [eHonnef/py-jellyfin-metadata-generator#2]
I get an error because of missing config.json

(base) formula1$ python3 Main.py ~/Documents/formula1/
Traceback (most recent call last):
  File "/Users/mac/Documents/py-jellyfin-metadata-generator/formula1/Main.py", line 21, in <module>
    gen = Generator(args.basefolder, args.mapped_folder)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kristgn/Documents/py-jellyfin-metadata-generator/formula1/Generator.py", line 25, in __init__
    self.config = json.load(open(f"{os.path.dirname(generator_module_path)}/config.json", "r"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mac/Documents/py-jellyfin-metadata-generator/formula1/config.json'

**Comment by eHonnef** [comment]
Sorry, I forgot to upload the `config.json` file in the last commit.
I uploaded in the last commit [f117f25](https://github.com/eHonnef/py-jellyfin-metadata-generator/commit/f117f2502f76a6829cbe30b7ed1e5264096a850b), check the readme for instructions on how to modify this file to your needs.
Give a try and let me know if everything is working :)
